# Generated by Django 2.2.5 on 2019-09-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotables_app', '0002_auto_20190929_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
