# Generated by Django 2.2.5 on 2019-09-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotables_app', '0003_quote_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='favorite',
            field=models.BooleanField(),
        ),
    ]
