# Generated by Django 2.2.5 on 2019-09-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotables_app', '0005_remove_quote_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_favorite',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
