# Generated by Django 2.2.5 on 2019-09-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotables_app', '0006_quote_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='quote',
            name='is_favorite',
            field=models.ManyToManyField(related_name='favorites', to='quotables_app.User'),
        ),
    ]
