# Generated by Django 2.2.5 on 2019-09-30 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotables_app', '0009_auto_20190929_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='favorited',
        ),
        migrations.AddField(
            model_name='quote',
            name='favorited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_quotes', to='quotables_app.User'),
        ),
    ]
